Fix font-office-code-pro file paths
The fonts have been moved to subdirectory, to differentiate from the dotted zero version.

Currently when I try to install I get this:

```bash
$ brew cask install font-office-code-pro
==> Downloading https://github.com/nathco/Office-Code-Pro/archive/master.zip
Error: It seems the hardlink source is not there: '/opt/homebrew-cask/Caskroom/font-office-code-pro/latest/Office-Code-Pro-master/Fonts/OTF/OfficeCodePro-Bold.otf'
```